# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/reference/xenial/
# https://docs.travis-ci.com/user/languages/python/
# https://docs.travis-ci.com/user/customizing-the-build/

dist: xenial
language: python
python:
    - "3.7"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -yq install hugo
    - pip install Pygments

script:
    - hugo

branches:
    only:
        - gh-pages

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: public
    target_branch: master # branch contains static content from Hugo
    on:
        branch: gh-pages  # branch contains source for Hugo
