baseURL = "http://tropicalisland.github.io/"
languageCode = "en-us"
title = "TropicalIsland"
copyright = "Copyright &copy; 2019 - Andrew McLean | Icon made by [Freepik](https://www.freepik.com/) from [www.flaticon.com](www.flaticon.com) is licensed by [CC 3.0 BY](https://creativecommons.org/licenses/by/3.0/)"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
author = "Andrew McLean"
github = "TropicalIsland"
gitlab = "AndyMcL"
linkedin = "andrew-mclean-8a2741149"

[params]
    tagline = "Here be ramblings on JavaScript, C++ and all sorts"
